# High-level write-throughput benchmarks


# these are common and can be overridden suite-wide
#
# note for bench_*_many, file size defaults to CHUNK, and SIZE = sum of
# all files
#
defines.SIZE = '1024*1024' # 1 MiB
defines.CHUNK = 64
defines.SEED = 42

# simulate this number of mounts or interuppted log-rotations
defines.SIM_MOUNTS = 10000
defines.SIM_ROTATES = 10 # ignored if not POWERLOSS
# simulated time, in nanoseconds, to run the test
defines.SIM_TIME = 0 # '60ULL*60ULL*1000ULL*1000ULL*1000ULL' # 1 hour
# simulation size in bytes
defines.SIM_SIZE = 0

# set this to true to skip bench warmup
defines.SKIP_WARMUP = false

# also bench read-only mount?
#
# TODO this isn't implemented yet
# defines.ROMOUNT = true

# run with simulated powerloss? defaults to a nice shutdown
defines.POWERLOSS = false

# emulate failed progs by adding noise?
defines.POWERLOSS_NOISE = false

# for spiffs, check the filesystem after a powerloss
#
# well this was a bit of a journey
#
# Spiffs comes with a SPIFFS_check function intended to validate and
# correct any errors after a known powerloss, but as far as I can tell,
# the best strategy is to just never call it. It just takes too long.
# (to be fair, we are benching on geometries larger than what spiffs was
# designed for)
#
# The good news is spiffs's metadata appears to be pl safe, and that's
# really what's important. See the spiffs docs (and confirmed so far in
# my testing):
# https://github.com/pellepl/spiffs/wiki/FAQ#
#     powerlosses-contd-when-should-i-run-spiffs_check
#
# So while we may end up with weird state and spurious errors (and
# duplicated data?) things should still work. Probably. And these sort
# of errors are _relatively_ easy to workaround at the application
# level.
#
# Note the goal here isn't really to measure powerloss properties. All
# three filesystems have different transaction models anyway. The goal
# is just to measure how long the filesystems take to get to some sort
# of functional state after a powerloss.
#
# available check modes:
# 0 => no pl check
# 1 => check after mount
# 2 => check after error
defines.POWERLOSS_CHECK = false

# how long before powerloss/shutdown, we choose a uniform number of
# nanoseconds between these
defines.POWER_MINTIME = 0
defines.POWER_MAXTIME = '10ULL*1000ULL*1000ULL*1000ULL' # 10 seconds
# alternatively, how long as defined by progs
defines.POWER_MINPROGS = 0
defines.POWER_MAXPROGS = 0

# spiffs is limited to 32-bit disks
if = 'BENCH_IFDEF_SPIFFS(DISK_SIZE < 0x100000000ULL, true)'

hooks.prog = 'bench_mount_bd_prog'
code = '''
    // include common bench helpers
    #include "benches/bench_helpers.h"

    // use longjmp to emulate powerlosses
    #include <setjmp.h>
    jmp_buf bench_mount_jmp;

    // progs since last mount
    int64_t bench_mount_progs = -1;
    uint32_t bench_mount_prng = 42;
    // run timing for simulated powerloss
    bench_sns_t bench_mount_start_time = -1;
    bench_sns_t bench_mount_stop_time = -1;
    int64_t bench_mount_start_progs = -1;
    int64_t bench_mount_stop_progs = -1;

    // hook prog
    int bench_mount_bd_prog(const struct lfs3_cfg *cfg, lfs3_block_t block,
            lfs3_off_t off, const void *buffer, lfs3_size_t size) {
        // time for powerloss?
        if (POWERLOSS
                && ((bench_mount_stop_time != -1
                        && BENCH_SIMTIME() >= bench_mount_stop_time)
                    || (bench_mount_stop_progs != -1
                        && bench_mount_progs > bench_mount_stop_progs))) {
            // write noise
            if (POWERLOSS_NOISE) {
                uint8_t noise[size];
                for (lfs3_size_t i = 0; i < size; i++) {
                    noise[i] = BENCH_PRNG(&bench_mount_prng);
                }
                int err = BENCH_BD_PROGNOHOOKS(cfg, block, off, noise, size);
                assert(!err);
            }

            // simulate powerloss
            longjmp(bench_mount_jmp, 1);
        }

        int err = BENCH_BD_PROGNOHOOKS(cfg, block, off, buffer, size);
        // increment progs
        bench_mount_progs += 1;
        return err;
    }
'''


# logging write throughput
#
# two big differences from seq:
# 1. fruncate/rotations instead of rewind+truncate
# 2. sync called on every write
[cases.bench_mount_logging]
defines.FRUNCATE = false
code = '''
    #if defined(LFS3)
    lfs3_t lfs3;
    lfs3_format(&lfs3, LFS3_F_RDWR, CFG) => 0;
    lfs3_mount(&lfs3, LFS3_M_RDWR | LFS3_M_MKCONSISTENT, CFG) => 0;
    #elif defined(LFS2)
    lfs2_t lfs2;
    lfs2_format(&lfs2, CFG_LFS2) => 0;
    lfs2_mount(&lfs2, CFG_LFS2) => 0;
    lfs2_fs_mkconsistent(&lfs2) => 0;
    #elif defined(SPIFFS)
    spiffs spiffs;
    spiffs.user_data = CFG;
    uint8_t *work_buffer = malloc(2*SPAGE_SIZE);
    uint8_t *fd_buffer = malloc(FD_SIZE);
    uint8_t *scache_buffer = malloc(SCACHE_SIZE);
    // spiffs format without magic just needs a disk erase
    SPIFFS_mount(&spiffs, (spiffs_config*)CFG_SPIFFS, work_buffer,
            fd_buffer, FD_SIZE,
            scache_buffer, SCACHE_SIZE,
            NULL) => 0;
    #elif defined(YAFFS2)
    // note this implicitly zeros yaffs_dev
    struct yaffs_dev yaffs2 = {
        .driver_context = CFG,
        .param = CFG_YAFFS2->param,
        .drv = CFG_YAFFS2->drv,
    };
    yaffs_add_device(&yaffs2);
    yaffs_format("/", false, false, false) => 0;
    yaffs_mount("/") => 0;
    #endif
    if (!SKIP_WARMUP) {
        BENCH_STACK_PAUSE();
        BENCH_HEAP_PAUSE();
        #if defined(LFS3)
        int err = bench_helpers_warmup(CFG, &lfs3);
        #elif defined(LFS2)
        int err = bench_helpers_warmup(CFG, &lfs2);
        #elif defined(SPIFFS)
        int err = bench_helpers_warmup(CFG, &spiffs);
        #elif defined(YAFFS2)
        int err = bench_helpers_warmup(CFG, &yaffs2);
        #endif
        if (err) {
            LFS3_ERROR("Bench warmup failed: %d", err);
            return;
        }
        BENCH_HEAP_RESUME();
        BENCH_STACK_RESUME();
    }
    uint32_t prng = SEED;

    // create the log file before our main loop, this avoids create cost
    // getting dragged into our mount + open path
    //
    // yes we pay for creates during logrotation later, but this is only
    // included in write cost, not mount + open cost
    //
    // this hits yaffs2 especially hard because create forces the
    // current checkpoint to be erased, resulting in a one-time spike
    // when mount + open creates the initial file
    #if defined(LFS3)
    lfs3_file_t file;
    lfs3_file_open(&lfs3, &file, "bench_log",
            LFS3_O_WRONLY | LFS3_O_CREAT | LFS3_O_EXCL | LFS3_O_APPEND) => 0;
    lfs3_file_close(&lfs3, &file) => 0;
    #elif defined(LFS2)
    lfs2_file_t file;
    lfs2_file_open(&lfs2, &file, "bench_log",
            LFS2_O_WRONLY | LFS2_O_CREAT | LFS3_O_EXCL | LFS2_O_APPEND) => 0;
    lfs3_file_close(&lfs2, &file) => 0;
    #elif defined(SPIFFS)
    spiffs_file fd = SPIFFS_open(&spiffs, "bench_log",
            SPIFFS_WRONLY | SPIFFS_CREAT | SPIFFS_EXCL | SPIFFS_APPEND, 0777);
    assert(fd >= 0);
    SPIFFS_close(&spiffs, fd) => 0;
    #elif defined(YAFFS2)
    int fd = yaffs_open("bench_log",
            O_WRONLY | O_CREAT | O_EXCL | O_APPEND, 0777);
    assert(fd >= 0);
    yaffs_close(fd) => 0;
    #endif

    // start unmounted
    #if defined(LFS3)
    lfs3_unmount(&lfs3) => 0;
    #elif defined(LFS2)
    lfs2_unmount(&lfs2) => 0;
    #elif defined(SPIFFS)
    SPIFFS_unmount(&spiffs);
    #elif defined(YAFFS2)
    yaffs_unmount("/") => 0;
    yaffs_remove_device(&yaffs2);
    #endif

    // reset our timer
    BENCH_SIMRESET();

    // ok, one of these needs to be non-zero
    LFS3_ASSERT(SIM_MOUNTS > 0
            || (SIM_ROTATES > 0 && !POWERLOSS)
            || SIM_TIME > 0
            || SIM_SIZE > 0);
    uint64_t mounts = 0;
    uint64_t written = 0;
    uint64_t grms = 0;
    uint64_t rotates = 0;
    bool in_rotation = false;
    int mkconsistented = -1;
    // this is where we end up after powerloss
    setjmp(bench_mount_jmp);
    BENCH_ABORT("mount");
    BENCH_ABORT("mkconsistent");
    BENCH_ABORT("open");
    BENCH_ABORT("write");
    BENCH_ABORT("close");
    BENCH_ABORT("unmount");
    // did we interrupt a log-rotation?
    if (in_rotation) {
        rotates += 1;
        in_rotation = false;
    }
    // if we didn't need mkconsistent, report 0 so percentile
    // measurements make sense
    if (mkconsistented == 0) {
        BENCH_START("mkconsistent");
        BENCH_STOP("mkconsistent", mounts);
    }
    mkconsistented = 0;
    while (!((SIM_MOUNTS || (SIM_ROTATES && !POWERLOSS))
                && mounts >= (uint64_t)SIM_MOUNTS
                && (!POWERLOSS || rotates >= (uint64_t)SIM_ROTATES))
            && !(SIM_SIZE && written >= (uint64_t)SIM_SIZE)
            && !(SIM_TIME && BENCH_SIMTIME() >= SIM_TIME)) {
        // reset progs
        bench_mount_progs = 0;
        // how long to run this loop?
        if (POWER_MINTIME || POWER_MAXTIME) {
            bench_mount_start_time = BENCH_SIMTIME();
            bench_mount_stop_time = bench_mount_start_time
                    + POWER_MINTIME
                    + (BENCH_PRNG(&prng) % (POWER_MAXTIME+1 - POWER_MINTIME));
        }
        if (POWER_MINPROGS || POWER_MAXPROGS) {
            bench_mount_start_progs = 0;
            bench_mount_stop_progs = bench_mount_start_progs
                    + POWER_MINPROGS
                    + (BENCH_PRNG(&prng) % (POWER_MAXPROGS+1 - POWER_MINPROGS));
        }

        // TODO readonly mount?

        // measure mount time
        BENCH_START("mount");
        mounts += 1;
        #if defined(LFS3)
        lfs3_mount(&lfs3, LFS3_M_RDWR, CFG) => 0;
        // keep track of how many grms we've seen
        if (lfs3.grm.queue[0]) {
            grms += 1;
        }
        #elif defined(LFS2)
        lfs2_mount(&lfs2, CFG_LFS2) => 0;
        #elif defined(SPIFFS)
        SPIFFS_mount(&spiffs, (spiffs_config*)CFG_SPIFFS, work_buffer,
                fd_buffer, FD_SIZE,
                scache_buffer, SCACHE_SIZE,
                NULL) => 0;
        // check the filesystem for errors after powerlos?
        //
        // note this takes literally forever, see above
        if (POWERLOSS_CHECK == 1 && POWERLOSS) {
            BENCH_START("mkconsistent");
            SPIFFS_check(&spiffs) => 0;
            mkconsistented = 1;
            BENCH_STOP("mkconsistent", mounts);
        }
        #elif defined(YAFFS2)
        // yaffs2 uses some global state we need to reset
        extern struct list_head yaffsfs_deviceList;
        INIT_LIST_HEAD(&yaffsfs_deviceList);
        extern int yaffsfs_handlesInitialised;
        yaffsfs_handlesInitialised = false;
        // yes, yaffs2 needs this to be zeroed
        yaffs2 = (struct yaffs_dev){
            .driver_context = CFG,
            .param = CFG_YAFFS2->param,
            .drv = CFG_YAFFS2->drv,
        };
        yaffs_add_device(&yaffs2);
        yaffs_mount("/") => 0;
        #endif
        BENCH_STOP("mount", mounts);

        // include mkconsistent cost for fairness, note inconsistent
        // mounts are the same as read-only mounts
        #if defined(LFS3)
        BENCH_START("mkconsistent");
        lfs3_fs_mkconsistent(&lfs3) => 0;
        mkconsistented = 1;
        BENCH_STOP("mkconsistent", mounts);
        #elif defined(LFS2)
        BENCH_START("mkconsistent");
        lfs2_fs_mkconsistent(&lfs2) => 0;
        mkconsistented = 1;
        BENCH_STOP("mkconsistent", mounts);
        #elif defined(SPIFFS)
        #elif defined(YAFFS2)
        #endif

        // open a file
        //
        // note we don't create here, see above
        BENCH_START("open");
        #if defined(LFS3)
        lfs3_file_t file;
        lfs3_file_open(&lfs3, &file, "bench_log",
                LFS3_O_WRONLY | LFS3_O_CREAT | LFS3_O_APPEND) => 0;
        #elif defined(LFS2)
        lfs2_file_t file;
        lfs2_file_open(&lfs2, &file, "bench_log",
                LFS2_O_WRONLY | LFS2_O_CREAT | LFS2_O_APPEND) => 0;
        #elif defined(SPIFFS)
        spiffs_file fd = SPIFFS_open(&spiffs, "bench_log",
                SPIFFS_WRONLY | SPIFFS_CREAT | SPIFFS_APPEND, 0777);
        assert(fd >= 0);
        #elif defined(YAFFS2)
        int fd = yaffs_open("bench_log",
                O_WRONLY | O_CREAT | O_APPEND, 0777);
        assert(fd >= 0);
        #endif
        BENCH_STOP("open", mounts);
        while (!((SIM_MOUNTS || (SIM_ROTATES && !POWERLOSS))
                    && mounts >= (uint64_t)SIM_MOUNTS
                    && (!POWERLOSS || rotates >= (uint64_t)SIM_ROTATES))
                && !(SIM_SIZE && written >= (uint64_t)SIM_SIZE)
                && !(SIM_TIME && BENCH_SIMTIME() >= SIM_TIME)
                // time to reboot?
                && (POWERLOSS
                    || !((bench_mount_stop_time != -1
                            && BENCH_SIMTIME() >= bench_mount_stop_time)
                        || (bench_mount_stop_progs != -1
                            && bench_mount_progs > bench_mount_stop_progs)))) {
            BENCH_START("write");
            // append to log
            uint8_t wbuf[CHUNK];
            for (lfs3_size_t j = 0; j < CHUNK; j++) {
                wbuf[j] = 'a' + (BENCH_PRNG(&prng) % 26);
            }
            #if defined(LFS3)
            lfs3_file_write(&lfs3, &file, wbuf, CHUNK) => CHUNK;
            #elif defined(LFS2)
            lfs2_file_write(&lfs2, &file, wbuf, CHUNK) => CHUNK;
            #elif defined(SPIFFS)
            SPIFFS_write(&spiffs, fd, wbuf, CHUNK) => CHUNK;
            #elif defined(YAFFS2)
            yaffs_write(fd, wbuf, CHUNK) => CHUNK;
            #endif

            // sync
            #if defined(LFS3)
            lfs3_file_sync(&lfs3, &file) => 0;
            #elif defined(LFS2)
            lfs2_file_sync(&lfs2, &file) => 0;
            #elif defined(SPIFFS)
            s32_t d = SPIFFS_fflush(&spiffs, fd);
            if (POWERLOSS_CHECK == 1) {
                assert(d >= 0);
            } else if (POWERLOSS_CHECK == 2) {
                // uh oh, need to run spiffs check to fix things? this is
                // _very_ expensive
                //
                // note this takes literally forever, see above
                if (d < 0) {
                    BENCH_START("mkconsistent");
                    SPIFFS_check(&spiffs) => 0;
                    mkconsistented = 1;
                    BENCH_STOP("mkconsistent", mounts);
                    d = SPIFFS_fflush(&spiffs, fd);
                    assert(d >= 0);
                }
            } else {
                // these are the known errors we can encounter after
                // powerloss
                assert(d >= 0
                        || d == SPIFFS_ERR_DELETED
                        || d == SPIFFS_ERR_INDEX_REF_FREE);
            }
            #elif defined(YAFFS2)
            yaffs_fsync(fd) => 0;
            #endif

            // for v3, fruncate, for v2, rotate if full
            //
            // unlike litmus benchmarks we just use SIZE here
            in_rotation = true;
            #if defined(LFS3)
            lfs3_soff_t size = lfs3_file_size(&lfs3, &file);
            assert(size >= 0);
            if (FRUNCATE) {
                if (size > SIZE) {
                    lfs3_file_fruncate(&lfs3, &file, SIZE) => 0;
                }
            } else {
                if (size >= SIZE) {
                    lfs3_file_close(&lfs3, &file) => 0;
                    lfs3_rename(&lfs3, "bench_log", "bench_log.1") => 0;
                    lfs3_file_open(&lfs3, &file, "bench_log",
                            LFS3_O_WRONLY
                                | LFS3_O_CREAT
                                | LFS3_O_EXCL
                                | LFS3_O_APPEND) => 0;
                }
            }
            #elif defined(LFS2)
            lfs3_soff_t size = lfs2_file_size(&lfs2, &file);
            assert(size >= 0);
            if (size >= SIZE) {
                lfs2_file_close(&lfs2, &file) => 0;
                lfs2_rename(&lfs2, "bench_log", "bench_log.1") => 0;
                lfs2_file_open(&lfs2, &file, "bench_log",
                        LFS2_O_WRONLY
                            | LFS2_O_CREAT
                            | LFS2_O_EXCL
                            | LFS2_O_APPEND) => 0;
            }
            #elif defined(SPIFFS)
            spiffs_stat stat;
            SPIFFS_fstat(&spiffs, fd, &stat) => 0;
            assert(stat.size >= 0);
            if (stat.size >= SIZE) {
                SPIFFS_close(&spiffs, fd) => 0;
                int err = SPIFFS_remove(&spiffs, "bench_log.1");
                assert(!err || err == SPIFFS_ERR_NOT_FOUND);
                SPIFFS_rename(&spiffs, "bench_log", "bench_log.1") => 0;
                fd = SPIFFS_open(&spiffs, "bench_log",
                        SPIFFS_WRONLY
                            | SPIFFS_CREAT
                            | SPIFFS_EXCL
                            | SPIFFS_APPEND, 0777);
                assert(fd >= 0);
            }
            #elif defined(YAFFS2)
            struct yaffs_stat stat;
            yaffs_fstat(fd, &stat) => 0;
            if (stat.st_size >= SIZE) {
                yaffs_close(fd) => 0;
                yaffs_rename("bench_log", "bench_log.1") => 0;
                fd = yaffs_open("bench_log",
                        O_WRONLY | O_CREAT | O_EXCL | O_APPEND, 0777);
                assert(fd >= 0);
            }
            #endif
            in_rotation = false;

            written += CHUNK;
            BENCH_STOP("write", written);
        }
        // close
        BENCH_START("close");
        #if defined(LFS3)
        lfs3_file_close(&lfs3, &file) => 0;
        #elif defined(LFS2)
        lfs2_file_close(&lfs2, &file) => 0;
        #elif defined(SPIFFS)
        SPIFFS_close(&spiffs, fd) => 0;
        #elif defined(YAFFS2)
        yaffs_close(fd) => 0;
        #endif
        BENCH_STOP("close", mounts);

        // unmount
        BENCH_START("unmount");
        #if defined(LFS3)
        lfs3_unmount(&lfs3) => 0;
        #elif defined(LFS2)
        lfs2_unmount(&lfs2) => 0;
        #elif defined(SPIFFS)
        SPIFFS_unmount(&spiffs);
        #elif defined(YAFFS2)
        yaffs_unmount("/") => 0;
        yaffs_remove_device(&yaffs2);
        #endif
        BENCH_STOP("unmount", mounts);
    }

    // report the number of interrupted log-rotations, note this may be
    // different from grms
    BENCH_RESULT("rotates", mounts, rotates);
    // report the number of grms
    #ifdef LFS3
    BENCH_RESULT("grms", mounts, grms);
    #endif

    // other cleanup?
    #if defined(LFS3)
    #elif defined(LFS2)
    #elif defined(SPIFFS)
    free(work_buffer);
    free(fd_buffer);
    free(scache_buffer);
    #elif defined(YAFFS2)
    #endif
'''

