# Bench our high-level metadata tree in the core of littlefs

# maximize lookahead buffer, we don't actually gc so we only get one pass
# of the disk for these tests
defines.LOOKAHEAD_SIZE = '(BLOCK_COUNT+8-1) / 8'

[cases.bench_mtree]
# 0 = in-order
# 1 = reversed-order
# 2 = random-order
defines.ORDER = [0, 1, 2]
defines.N = 1024
defines.STEP = 1
defines.SEED = 42
defines.SIZE = 4
in = 'littlefs3/lfs.c'
code = '''
    lfs_t lfs;
    lfsr_format(&lfs, LFS_F_RDWR, CFG) => 0;
    lfsr_mount(&lfs, LFS_M_RDWR, CFG) => 0;

    // create an mtree with N entries
    uint32_t prng = SEED;
    for (lfs_size_t i = 0; i < N; i++) {
        lfsr_mid_t i_
                = (ORDER == 0) ? i
                : (ORDER == 1) ? N-1-i
                : BENCH_PRNG(&prng) % N;
        char name[256];
        sprintf(name, "e%05d", i_);
        uint8_t wbuf[SIZE];
        memset(wbuf, 'a'+(BENCH_PRNG(&prng) % 26), SIZE);

        if ((i+1) % STEP == 0) {
            BENCH_START("commit", i+1);
        }
        lfsr_mdir_t mdir;
        lfsr_tag_t tag;
        lfsr_data_t data;
        int err = lfsr_mtree_namelookup(&lfs,
                0, name, strlen(name),
                &mdir, &tag, &data);
        assert(!err || err == LFS_ERR_NOENT);
        // new entry?
        if (err == LFS_ERR_NOENT) {
            lfsr_mdir_commit(&lfs, &mdir, LFSR_RATTRS(
                    LFSR_RATTR_NAME(
                        LFSR_TAG_REG, +1,
                        0, name, strlen(name)),
                    LFSR_RATTR_BUF(
                        LFSR_TAG_DATA, 0,
                        wbuf, SIZE))) => 0;
            
        // collision?
        } else {
            lfsr_mdir_commit(&lfs, &mdir, LFSR_RATTRS(
                    LFSR_RATTR_BUF(
                        LFSR_TAG_DATA, 0,
                        wbuf, SIZE))) => 0;
        }
        if ((i+1) % STEP == 0) {
            BENCH_STOP("commit");
        }

        if ((i+1) % STEP == 0) {
            // measure name lookups
            BENCH_START("namelookup", i+1);
            lfsr_mid_t i_ = BENCH_PRNG(&prng) % N;
            sprintf(name, "e%05d", i_);
            lfsr_mdir_t mdir;
            lfsr_tag_t tag;
            lfsr_data_t data;
            int err = lfsr_mtree_namelookup(&lfs,
                    0, name, strlen(name),
                    &mdir, &tag, &data);
            assert(!err || err == LFS_ERR_NOENT);
            if (!err) {
                assert(tag == LFSR_TAG_REG);
            }
            BENCH_STOP("namelookup");

            // measure mid lookups
            //
            // we use mid found by name lookup so we know mid is valid
            BENCH_START("lookup", i+STEP);
            lfsr_mtree_lookup(&lfs, mdir.mid,
                    &mdir) => 0;
            BENCH_STOP("lookup");

            // measure traversal cost
            BENCH_START("traversal", i+STEP);
            lfsr_traversal_t t;
            lfsr_traversal_open(&lfs, &t, 0) => 0;
            while (true) {
                struct lfs_tinfo tinfo;
                int err = lfsr_traversal_read(&lfs, &t,
                        &tinfo);
                assert(!err || err == LFS_ERR_NOENT);
                if (err == LFS_ERR_NOENT) {
                    break;
                }
            }
            lfsr_traversal_close(&lfs, &t) => 0;
            BENCH_STOP("traversal");

            // measure disk usage
            lfs_off_t count = 0;

            lfsr_traversal_open(&lfs, &t, 0) => 0;
            while (true) {
                struct lfs_tinfo tinfo;
                int err = lfsr_traversal_read(&lfs, &t,
                        &tinfo);
                assert(!err || err == LFS_ERR_NOENT);
                if (err == LFS_ERR_NOENT) {
                    break;
                }

                count += 1;
            }
            lfsr_traversal_close(&lfs, &t) => 0;

            BENCH_RESULT("usage", i+1,
                    (uintmax_t)count * CFG->block_size);
        }
    }

    lfsr_unmount(&lfs) => 0;
'''
